- app/src/main/java/org/transdroid/daemon/util/HttpHelper.java
Previously I had a self-signed certificate set up, and added the custom public key to the settings accordingly.
Now that I have acquired a real certificate, I could not get my server to work. After removing the server and re-adding the server, all did work.
I traced the problem to "ssl_trust_key" being "" (empty string) instead of null. When it is not null, it is treated like a custom key, even when it is empty. It is not possible to 'unset' the setting.
This PR should fix this issue. Unfortunately I was **not** able to setup a build environment to test it. Please review it carefully.
> Fix always failing SSL with empty sslTrustKey

- app/src/main/java/org/transdroid/daemon/Qbittorrent/QbittorrentAdapter.java
In qBittorrent 3.2.0, they changed around the API mildly, replacing a few paths, changing some numeric values passed as strings to be passed as numbers, and replacing the HTTP basic authentication with an API login request that provides a session cookie.
This patch, as far as I can tell/have tested, addresses all the relevant changes, and allows Transdroid to support both 3.2.0 along with any previously support versions (or at least 3.1.0, the one older version i tested against)
> Support for qBittorrent 3.2.0

- app/src/main/java/org/transdroid/core/app/settings/ApplicationSettings.java
Added a null-safe trim-method when reading up ServerSettings. 
This trim(..) is used for *server_address* and *server_localaddress*.
Tested to work as intended.
> Fix for #255) Whitespace around IP/hostname results in connection error

- app/src/main/java/org/transdroid/daemon/Daemon.java
- app/src/main/java/org/transdroid/daemon/Qbittorrent/QbittorrentAdapter.java
Since qBitTorrent added support for force recheck through its web API, and I missed that feature in Transdroid, I thought I would add it.
> Add force recheck command for qBittorrent

- app/src/main/java/org/transdroid/daemon/Rtorrent/RtorrentAdapter.java
I noticed some discrepencies between `ruTorrent` and `transdroid` UI around `stop` and `pause` actions and states:
<h1> `stop` action resulted in torrents in `pause` state on `ruTorrent` </h1>
With this PR we now use the same xmlrpc commands as `ruTorrent` for `{pause,resume,stop,start}{,All}` (https://github.com/Novik/ruTorrent/blob/31a395ee6c9bc756d92c4c038ad229e1393ac1aa/plugins/httprpc/action.php#L243-L262)
I was however not able to test `StopAll` and `StartAll` as I haven't found any usage of them on the UI (`INTENT_STOPALL` and `INTENT_STARTALL` never set, only read).
<h1> Torrent Status computation needed update to keep in sync with actions copied from `ruTorrent` </h1>
- needed more information (`is_open`) to compute torrent status as in ruTorrent.
- there is no `stopped` status …
> Fix stop/pause for rtorrent

- app/src/main/java/org/transdroid/core/app/settings/ApplicationSettings.java
header_defaultserver is a string everywhere else but here.
> Fix bug when removing a server. 

- app/src/main/java/org/transdroid/core/gui/search/FilePickerHelper.java
Fix for issue #405
Opening a native File Picker with MIME type "file/*" doesn't allow picking files - shows them as disabled.
Using "application/x-bittorrent" does work.
> Use "application/x-bittorrent" instead of "file/*" in File Picker

- app/src/main/java/org/transdroid/daemon/Daemon.java
Add `Deluge2Rpc` to `supportsAddByMagnetUrl` and `supportsRemoveWithData`
resolves https://github.com/erickok/transdroid/issues/508
> add missing support checks for Deluge2Rpc

- app/src/main/java/org/transdroid/daemon/Qbittorrent/QbittorrentAdapter.java
Support for the new qBittorrent API (v2.3.0) which is required for use with qBittorrent verison > 4.2.0.
Only issue I noted so far is that the "Set Label" feature can only set existing categories in qBittorrent to torrents, not create new ones. This is consistent with previous versions of Transdroid, so I decided against implementing a fix in this pull request. Might get around to it, but I dont use the Category feature myself :)
> New api support

- app/build.gradle
On Android Studio 3.6.1, AA was not finding the manifest file. This small change helped, coupled with #530.
> Fix build errors due to AndroidAnnotations

- app/src/main/java/org/transdroid/core/gui/TorrentsFragment.java
isResumed() was always returning false upon activity resume, so torrent updates from details activity were not being applied
steps to reproduce bug:
* view unabelled torrents list
* click into torrent details
* set a label
* wait for success
* press back
* torrent still in the unlabelled list
> fixed mimic label not working

- app/src/main/java/org/transdroid/core/gui/TorrentsActivity.java
bug: navigation list is missing labels
* load up TorrentsActivity
* click on a torrent to view details
* click back
* open up navigation menu, there are no labels
In case it's working, I've got "always destroy activities" turned on
> fixed missing navigation labels after returning to TorrentsActivity

- app/src/main/java/org/transdroid/daemon/BitComet/BitCometAdapter.java
The task id should be assigned from XML, not assumed to be the order number in the returned XML list.
The old code works only for BitComet v1.67 and earlier versions.
This fix is needed for BitComet v1.68 and later, and also compatible with old versions of BitComet.
> Fix task id parsing for BitComet v1.68 and later

- app/src/main/java/org/transdroid/daemon/task/AddByMagnetUrlTask.java
- app/src/main/java/org/transdroid/daemon/task/AddByUrlTask.java
The use case is fairly specific. This allows copying and pasting URLs from a command line session where the URL wraps inside the terminal, which injects whitespace in the middle of the URL. Removing the whitespace manually is tedious. This handles it in the app.
Risk: Low
> Remove all whitespace from URL when adding

- app/src/main/java/org/transdroid/daemon/adapters/deluge/DelugeAdapter.java
Fixes #583 
I put this MR in draft since I'm unable to check it locally right now.
Also, all adapters got different handling of this folder parameter (adding missing slash ahead, remove trailing slash, trimming), a better approach would be to add a common method for sanitizing this parameter (but `IDaemonAdapter` is an interface, not an abstract class...).
> Remove trailing slash from folder in deluge adapter

- app/src/main/java/org/transdroid/daemon/IDaemonAdapter.java
- app/src/main/java/org/transdroid/daemon/adapters/deluge/DelugeAdapter.java
- app/src/main/java/org/transdroid/daemon/adapters/qBittorrent/QBittorrentAdapter.java
Add logic to re-authenticate based on a max time (30mins) with deluge and qbittorrent
Closes https://github.com/erickok/transdroid/issues/602
> Re-authenticate for qbittorrent and deluge

- app/src/main/res/values-cs/strings.xml
- app/src/main/res/values-da/strings.xml
- app/src/main/res/values-de/strings.xml
- app/src/main/res/values-fa/strings.xml
- app/src/main/res/values-fr/strings.xml
- app/src/main/res/values-hu/strings.xml
- app/src/main/res/values-it/strings.xml
- app/src/main/res/values-ja/strings.xml
- app/src/main/res/values-ko/strings.xml
- app/src/main/res/values-nl/strings.xml
- app/src/main/res/values-pt-rBR/strings.xml
- app/src/main/res/values-pt/strings.xml
- app/src/main/res/values-ru/strings.xml
- app/src/main/res/values-sl/strings.xml
- app/src/main/res/values-sv/strings.xml
- app/src/main/res/values-tr/strings.xml
- app/src/main/res/values-zh-rCN/strings.xml
Seems like `pref_seedbox_xirviknofolder` was removed in favor of `pref_seedbox_xirvikfolderfallback` in https://github.com/erickok/transdroid/commit/29c3b3b0dc71f568e1b17f1d953f4d452736bece but the translated copies of `pref_seedbox_xirviknofolder` were not removed.
> Remove obsolete pref_seedbox_xirviknofolder from translated files

- app/src/main/java/org/transdroid/daemon/adapters/bitComet/BitCometAdapter.java
1. Fix torrent status to seeding for completed active torrents.
2. Fix int64 parsing for "bytes_downloaded" and "bytes_uploaded"
3. Parsing "hashing" and "queued" status.
> Fix torrent status parsing for BitComet.

- app/src/main/java/org/transdroid/daemon/Torrent.java
Show the pause button on torrent details if the torrent is queued.
Fixes https://github.com/erickok/transdroid/issues/636
> Allow pausing a torrent when queued

- app/src/main/java/org/transdroid/daemon/adapters/qBittorrent/QBittorrentAdapter.java
Fix setting limits on qbittorrent 4.1+
https://github.com/qbittorrent/qBittorrent/wiki/WebUI-API-(qBittorrent-4.1)#set-global-download-limit
Fixes https://github.com/erickok/transdroid/issues/630
Tested with qBittorrent 4.3.9.
> qBittorrent 4.x+: Fix setting global upload and download limits

- app/src/main/java/org/transdroid/daemon/adapters/bitComet/BitCometAdapter.java
Use `/panel/task_add_magnet_result` when passing link to torrent files.
Fixes https://github.com/erickok/transdroid/issues/622
> BitComet: Update to use add magnet url for passed links

- app/src/main/java/org/transdroid/daemon/adapters/bitComet/BitCometAdapter.java
Remove unprintable char from `BitCometAdapter.java` .
Fixes https://github.com/erickok/transdroid/issues/627
> Remove illegal character from BitCometAdapter.java

- app/src/main/java/org/transdroid/daemon/adapters/qBittorrent/QBittorrentAdapter.java
Fixes working with qBittorrent when there's no categories.  `names()` returns `null` if the `JSONObject` is `{}`
Introduced in https://github.com/erickok/transdroid/pull/625
> qBittorrent: Fix working with no categories

- app/build.gradle
Update gradle deps
Increase `minSdkVersion` to `21` to avoid `Error:Cannot fit requested classes in a single dex file`
Increase `compileSdkVersion` and `targetSdkVersion` to 33 to work with new dep versions
Add 
```
implementation "androidx.lifecycle:lifecycle-viewmodel:2.5.1"
implementation "androidx.lifecycle:lifecycle-viewmodel-ktx:2.5.1"
```
to avoid `Duplicate class androidx.lifecycle.ViewModelLazy found in modules jetified-lifecycle-viewmodel-ktx-2.3.1-runtime (androidx.lifecycle:lifecycle-viewmodel-ktx:2.3.1) and lifecycle-viewmodel-2.5.1-runtime (androidx.lifecycle:lifecycle-viewmodel:2.5.1)`
> Update gradle dependencies

- app/src/main/java/org/transdroid/daemon/Daemon.java
Remove bitcomet from the supportsStoppingStarting so we don't show an extra stop button.
Torrent stopped:
Torrent started:
Fixes https://github.com/erickok/transdroid/issues/634
> Dont show stop button on Bitcomet

- app/src/main/java/org/transdroid/core/gui/TorrentsActivity.java
- app/src/main/java/org/transdroid/daemon/task/AddByMagnetUrlTask.java
Move the stripping of whitespace from a torrent link to before the URL decode happens.
Hopefully this will still remove unwanted whitespace introduced by copy paste from the terminal as in https://github.com/erickok/transdroid/pull/551 while still encoding the spaces present in a magnet link as in https://github.com/erickok/transdroid/issues/618.
Fixes https://github.com/erickok/transdroid/issues/618
> Fix stripping space out of links but keep spaces in name intact
