erickok/transdroid

app/src/main/java/org/transdroid/daemon/Rtorrent/RtorrentAdapter.java

Latest rtorrent changed names of many RPC commands.

Fix rtorrent support

---

app/src/main/res/layout/actionbar_serverstatus.xml
app/src/main/res/values-land/dimens.xml
app/src/main/res/values-sw600dp/dimens.xml
app/src/main/res/values/dimens.xml

I just increased the with of the text fields by a few dp.
I added a tools:background color to the layout, cause it's black on black in the editor otherwise for me.
Also, I noticed that the text in those fields were using dp instead of sp for their size, so I changed this as well (assuming it was not done on purpose).

Fix for issue 336

---

app/src/main/java/org/transdroid/daemon/Deluge/DelugeAdapter.java
build.gradle
gradle/wrapper/gradle-wrapper.properties

This commit aims to fix issue #355 which is caused by the change on the Deluge codebase [http://git.deluge-torrent.org/deluge/commit/?h=1.3-stable&id=318ab179865e0707d7945edc3a13a464a108d583](here) also referenced [http://forum.deluge-torrent.org/viewtopic.php?t=54428](here).
This is my first Github-based Pull Request, let me know if I've done something wrong 👍

Issue #355 - Fix compatibility with latest Deluge. Also upgrade Gradle.

---

app/src/main/java/org/transdroid/core/app/settings/ApplicationSettings.java

Fix remove rss feeder settings

---

app/src/main/java/org/transdroid/daemon/Synology/SynologyAdapter.java

AddByFile now works instead of throwing a NPE.

Add Synology AddByFile Support

---

app/src/main/java/org/transdroid/core/app/settings/ApplicationSettings.java
app/src/main/java/org/transdroid/core/gui/search/SearchActivity.java
app/src/main/java/org/transdroid/core/gui/search/SearchResultsFragment.java
app/src/main/res/menu/activity_search.xml
app/src/main/res/values/strings.xml

Support a Sort-By action in Search Activity toolbar.

Add Sort-By Action to Search Activity

---

app/src/main/java/org/transdroid/core/gui/settings/PreferenceCompatActivity.java

Remove setTitle() call which was causing NPE on orientation change

---

README.md

two beautiful buttons with links to fdroid and google play store

Add buttons for fdroid and google play store

---

app/src/main/java/org/transdroid/core/gui/TorrentsActivity.java
app/src/main/java/org/transdroid/core/gui/remoterss/RemoteRssActivity.java
app/src/main/java/org/transdroid/core/gui/remoterss/RemoteRssFragment.java
app/src/main/java/org/transdroid/core/gui/remoterss/data/RemoteRssSupplier.java
app/src/main/java/org/transdroid/daemon/Daemon.java
app/src/main/java/org/transdroid/daemon/Deluge/DelugeCommon.java
app/src/main/java/org/transdroid/daemon/Deluge/DelugeRemoteRssChannel.java
app/src/main/java/org/transdroid/daemon/Deluge/DelugeRemoteRssItem.java
app/src/main/java/org/transdroid/daemon/Deluge/DelugeRpcAdapter.java
app/src/main/java/org/transdroid/daemon/Utorrent/UtorrentAdapter.java
app/src/main/res/layout/fragment_remoterss.xml
app/src/main/res/values/strings.xml

Add Remote RSS Support to Deluge RPC Adapter
Also:
* Make Remote RSS activity support "Swipe To Refresh"
* Preserve scroll position on orientation changes.

Deluge Remote RSS

---

app/src/main/java/org/transdroid/daemon/Deluge/DelugeAdapter.java

This was broken during refactoring with RPC adapter.
Resolves #427

Fix adding torrent file with Deluge Web #427

---

.gitignore
app/build.gradle
keystore.properties.example

These commits will allow building the app on other peoples' systems.

Fix builds for others.

---

app/src/main/java/org/transdroid/daemon/Daemon.java
app/src/main/java/org/transdroid/daemon/Deluge/DelugeRpcAdapter.java
app/src/main/java/org/transdroid/daemon/Deluge/DelugeRpcClient.java
app/src/main/res/values/strings.xml

Fixes #502.
Unfortunatley there is no good way to detect the version, so added another choice.

Add support for Deluge V2 RPC.

---

app/src/main/java/org/transdroid/core/gui/DetailsActivity.java
app/src/main/java/org/transdroid/core/gui/DetailsFragment.java
app/src/main/java/org/transdroid/core/gui/TorrentTasksExecutor.java
app/src/main/java/org/transdroid/core/gui/TorrentsActivity.java
app/src/main/java/org/transdroid/daemon/Daemon.java
app/src/main/java/org/transdroid/daemon/DaemonMethod.java
app/src/main/java/org/transdroid/daemon/Qbittorrent/QbittorrentAdapter.java
app/src/main/java/org/transdroid/daemon/Torrent.java
app/src/main/java/org/transdroid/daemon/task/ToggleFirstLastPieceDownloadTask.java
app/src/main/java/org/transdroid/daemon/task/ToggleSequentialDownloadTask.java
app/src/main/res/menu/fragment_details.xml
app/src/main/res/values-ru/strings.xml
app/src/main/res/values/strings.xml

Following up on an old issue of mine (#191 ). Finally got around to it!
Fully implemented sequential download and first-last piece priority for qBittorrent. Tested on a real device. Let me know if anything is amiss.

Add qbittorrent features

---

app/src/main/java/org/transdroid/core/gui/DetailsFragment.java
app/src/main/java/org/transdroid/core/gui/lists/DetailsAdapter.java
app/src/main/java/org/transdroid/core/gui/lists/PiecesMapView.java
app/src/main/java/org/transdroid/daemon/Qbittorrent/QbittorrentAdapter.java
app/src/main/java/org/transdroid/daemon/TorrentDetails.java
app/src/main/res/values/strings.xml

Added a piece map view for torrent details. Implemented for qBittorrent server, but should be trivial to adapt to any other torrent client that supports piece state through API.
White are not downloaded areas,
Blue are currently downloading areas,
Light green are partially complete areas,
Darker green are complete areas

Piece progress view

---

app/src/main/java/org/transdroid/core/gui/navigation/Label.java

show unlabelled torrents at the top of filter list

---

app/src/main/res/layout/fragment_details_header.xml

short | long
------ | ------
short | long
------ | ------

fix squishy date on TorrentDetails when label is too long

---

app/src/main/java/org/transdroid/daemon/TorrentDetails.java

* open torrent details
* press home
* app crashes

fix crash on TorrentDetails activity

---

app/src/main/java/org/transdroid/core/gui/rss/RssFeedsActivity.java

only if
* remote server supports it AND
* remote rss feeds are set up AND
* you dont use local rss feeds

automatically switch to remote RSS feeds

---

app/src/main/java/org/transdroid/daemon/adapters/uTorrent/UTorrentAdapter.java

added cookieStore to UtorrentAdapter
should fix #416
been using it for a month and has worked fine.
haven't noticed any other issues with the adapter

#416 fix file upload not working for utorrent

---

app/src/main/java/org/transdroid/daemon/Torrent.java
app/src/main/java/org/transdroid/daemon/adapters/qBittorrent/QBittorrentAdapter.java

Fixes #558
I also refactored the Torrent file to use a builder pattern, as I found it much more readable. If you've no objections, I'll roll it out to the other adapters as well (I restricted the changes to the QBittorentAdapter since that is the one I was working on)

Fix qbittorrent path population

---

app/src/main/java/org/transdroid/daemon/adapters/deluge/DelugeAdapter.java

Made some cleanups and fixed to the deluge adapter (I missed syncing the initialization on my prior fix)

Adding sync issue cleanup

---

app/build.gradle
app/src/main/res/layout/dialog_about.xml

Add version in the about page, including version code
append .debug if debug build

Add version in about screen

---

app/src/main/java/org/transdroid/daemon/adapters/qBittorrent/QBittorrentAdapter.java

Store the qBittorrent priority values in the adapter class and then adjust when the api version is known.
Fixes https://github.com/erickok/transdroid/issues/619

Fix setting High file priority on qBittorrent 3.2.x+

---

app/build.gradle
app/src/main/AndroidManifest.xml
build.gradle
gradle/wrapper/gradle-wrapper.properties

Update gradle plugin to latest version.
This builds and runs in my AndroidStudio; not sure if there are other things to test?
Fixes https://github.com/erickok/transdroid/issues/640

Update gradle plugin to 7.3.1

---

app/src/main/java/org/transdroid/daemon/adapters/bitComet/BitCometAdapter.java

Check for 401 or 403 in response in `makeRequest` in bitComet and throw an appropriate `DaemonException`
Allow this new `DaemonException` to reach the top so it can return a `DaemonTaskFailureResult`
Make that top return of `DaemonTaskFailureResult` use the thrown `DaemonException`
Fixes https://github.com/erickok/transdroid/issues/645

handle authorization issue in bitComet

---

app/src/main/java/org/transdroid/daemon/adapters/qBittorrent/QBittorrentAdapter.java

Use start/stop instead of resume/pause for qBittorrent 5.
Fixes https://github.com/erickok/transdroid/issues/672

Use start/stop for qbittorrent 5
